import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createWorkflow,WF,workflowEventApproved} from '../lib/events/workflow.js';
import {sourceActivities} from '../lib/events/catalog.js';
import {workflowRoutes} from '../lib/events/workflow-api.js';
const body={name:'合成活动',date:'2026-10-10',slot:'下午',position:'服务岗',capacity:2,serviceHours:2,trainingHours:0,travelHours:0,location:'合成场地',work:'合成服务',submit:false};
const student={accountId:'synthetic',studentId:'999990001',realName:'合成同学',email:'999990001@smail.nju.edu.cn',emailVerified:true};
function fixture(){let seq=0;const rows=Object.fromEntries(Object.values(WF).map(t=>[t,[]]));rows['登记审批']=[{_id:'app',活动名称:'源表新增活动',活动日期:'2026-10-11',活动类别:'公益活动',邮箱:'private@example.org'}];rows['活动报名总表']=[{_id:'old1',活动名称:'历史活动',活动类别:'公益活动',报名日期:'2026-10-12',报名时段:'上午',岗位:'宣传岗',姓名:'私密名字',学号:'private-sid',志愿时长:8,录入状态:'已录入'}];rows['市血液献血车排班表（模板表）']=[{_id:'blood',序号:'周一',点位:'新街口中央',活动时间:'上午 11~15点'}];
 const base={async getMetadata(){return{tables:Object.keys(rows).map(name=>({name}))};},async listRows(t,_v,_o,_c,s=0,n=500){return structuredClone(rows[t].slice(s,s+n));},async appendRow(t,row){const r={...row,_id:`r${++seq}`};rows[t].push(r);return{_id:r._id};},async updateRow(t,id,p){Object.assign(rows[t].find(r=>r._id===id),p);}};return {rows,w:createWorkflow(base)};
}
test('new table activity definitions appear with no identity leakage or historical hours inferred',async()=>{const f=fixture(),before=structuredClone(f.rows);const catalog=await f.w.sources();assert.equal(catalog.length,2);assert.equal(JSON.stringify(catalog).includes('private'),false);assert.equal(JSON.stringify(catalog).includes('私密名字'),false);assert.equal(catalog.find(c=>c.kind==='registrations').serviceHours,'');assert.deepEqual(f.rows,before);f.rows['登记审批'].push({_id:'new',活动名称:'刚新增活动'});assert.equal((await f.w.sources()).length,3);});
test('source adoption is stable, starts draft, needs same approval, and never migrates participants/totals',async()=>{const f=fixture(),key=(await f.w.sources()).find(s=>s.kind==='applications').key;const old=structuredClone(f.rows['活动报名总表']);const e=await f.w.adopt(key,body,'owner');assert.equal(e.状态,'草稿');assert.equal((await f.w.adopt(key,body,'owner'))._id,e._id);assert.equal(f.rows[WF.events].length,1);await assert.rejects(f.w.publish(e._id),{statusCode:409});await f.w.submit(e._id);await assert.rejects(f.w.approve(e._id,'owner'),{statusCode:403});await f.w.approve(e._id,'reviewer');await f.w.publish(e._id);assert.deepEqual(f.rows['活动报名总表'],old);assert.equal(f.rows[WF.registrations].length,0);assert.equal(f.rows[WF.ledger].length,0);});
test('editing increments version, resets approval and prevents editor approving own changes',async()=>{const f=fixture(),e=await f.w.create({...body,submit:true},'owner');await f.w.approve(e._id,'reviewer');assert.equal(workflowEventApproved(f.rows[WF.events][0]),true);await f.w.edit(e._id,{...body,name:'更新名称'},'editor');const updated=f.rows[WF.events][0];assert.equal(updated.申请版本,'2');assert.equal(updated.状态,'草稿');assert.equal(workflowEventApproved(updated),false);await f.w.submit(e._id);await assert.rejects(f.w.approve(e._id,'editor'),{statusCode:403});await f.w.approve(e._id,'reviewer');await f.w.publish(e._id);await assert.rejects(f.w.edit(e._id,body,'editor'),{statusCode:409});});
test('soft delete can restore, refuses any existing participation; close retains ledger sources',async()=>{const f=fixture(),e=await f.w.create(body,'owner');await f.w.archive(e._id);assert.equal(f.rows[WF.events][0].状态,'已归档');await f.w.restore(e._id);assert.equal(f.rows[WF.events][0].状态,'草稿');await f.w.submit(e._id);await f.w.approve(e._id,'reviewer');await f.w.publish(e._id);const r=await f.w.register(e._id,student);await assert.rejects(f.w.archive(e._id),{statusCode:409});await f.w.confirm(r._id);await f.w.checkin(r._id,'checker','合成证据');const l=await f.w.reviewHours(r._id,'checker');await f.w.approveHours(l._id,'reviewer');await f.w.close(e._id);assert.equal((await f.w.post(l._id)).serviceHours,2);});
test('ordinary, single blood and weekly blood templates all enter the same draft/review/publish path',async()=>{const f=fixture();const weekly=await f.w.prepareBloodWeek({monday:'2026-10-12',week:46,capacity:1,serviceHours:2,submit:false},'owner');assert.equal(weekly.events[0].状态,'草稿');const single=await f.w.create({...body,templateId:'blood_vehicle',location:'仙林学则路',slot:'下午 14~18点',week:45},'owner');assert.equal(JSON.parse(single.报名页配置).blood.mode,'blood_vehicle');for(const e of [single,weekly.events[0]]){await f.w.submit(e._id);await f.w.approve(e._id,'reviewer');await f.w.publish(e._id);}await assert.rejects(f.w.create({...body,templateId:'blood_vehicle',week:45},'owner'),{statusCode:400});});
test('raw table edits cannot bypass prepared config validation or approved digest',async()=>{const f=fixture(),e=await f.w.create({...body,submit:true},'owner');f.rows[WF.events][0].容量='20';await assert.rejects(f.w.approve(e._id,'reviewer'),{statusCode:409});await assert.rejects(f.w.create({...body,date:'2026-02-30'},'owner'),{statusCode:400});});
test('source group keys distinguish date/slot/position; no fuzzy title-only merging',()=>{const groups=sourceActivities([{活动名称:'相同活动',报名日期:'2026-10-10',报名时段:'上午',岗位:'A'},{活动名称:'相同活动',报名日期:'2026-10-10',报名时段:'下午',岗位:'A'},{活动名称:'相同活动',报名日期:'2026-10-10',报名时段:'上午',岗位:'B'}],[]);assert.equal(groups.length,3);assert.equal(new Set(groups.map(g=>g.key)).size,3);});
test('new CRUD/source API routes retain events scope, CSRF/origin guards and audit',async()=>{const f=fixture();let allow=false,csrf=true,audits=0;const c={getWorkflow:async()=>f.w,requireConsoleAccess:()=>allow?{username:'actor'}:null,requirePortalSession:()=>null,requireCsrf:()=>csrf,actor:()=> 'editor',readJson:async req=>req.body,json:(_r,status,payload)=>({status,payload}),audit:async()=>{audits++;}};const r={method:'POST',body:{key:'applications:app',config:body},headers:{host:'localhost'}};const url=new URL('http://localhost/api/volunteer/workflow/adopt');assert.equal(await workflowRoutes(r,null,url,c),undefined);allow=true;csrf=false;assert.equal(await workflowRoutes(r,null,url,c),undefined);csrf=true;r.headers.origin='https://evil.example';assert.equal((await workflowRoutes(r,null,url,c)).status,403);delete r.headers.origin;const out=await workflowRoutes(r,null,url,c);assert.equal(out.status,201);const edit=await workflowRoutes({...r,method:'PATCH',body:{...body,name:'已改'}},null,new URL(`http://localhost/api/volunteer/workflow/events/${out.payload.result._id}`),c);assert.equal(edit.status,200);assert.equal(audits,2);});
test('notice changes reset approval and require independent review; duplicate blood slot creation refused',async()=>{const f=fixture(),e=await f.w.create({...body,submit:true},'owner');await f.w.approve(e._id,'reviewer');await f.w.editNotice(e._id,'更新后的合成报名通知','editor');assert.equal(f.rows[WF.events][0].状态,'草稿');assert.equal(workflowEventApproved(f.rows[WF.events][0]),false);await f.w.submit(e._id);await assert.rejects(f.w.approve(e._id,'editor'),{statusCode:403});await f.w.approve(e._id,'reviewer');const blood={...body,templateId:'blood_vehicle',date:'2026-10-12',slot:'上午 11~15点',location:'新街口中央',week:46};await f.w.create(blood,'owner');await assert.rejects(f.w.create(blood,'owner'),{statusCode:409});});
test('super administrator can approve own activity and hours without bypassing evidence or idempotency',async()=>{
 const f=fixture(), e=await f.w.create({...body,submit:true},student.accountId);
 await assert.rejects(f.w.approve(e._id,student.accountId,'platform_admin'),{statusCode:403});
 await f.w.approve(e._id,student.accountId,'super_admin');await f.w.publish(e._id);
 const r=await f.w.register(e._id,student);await f.w.confirm(r._id);await f.w.checkin(r._id,student.accountId,'合成证据');
 const ledger=await f.w.reviewHours(r._id,student.accountId);
 await assert.rejects(f.w.approveHours(ledger._id,student.accountId,'platform_admin'),{statusCode:403});
 await f.w.approveHours(ledger._id,student.accountId,'super_admin');
 assert.equal((await f.w.post(ledger._id)).serviceHours,2);
 assert.equal((await f.w.post(ledger._id)).serviceHours,2);
 const changed=await f.w.create({...body,submit:true},'owner');f.rows[WF.events].find(r=>r._id===changed._id)['容量']='999';
 await assert.rejects(f.w.approve(changed._id,'owner','super_admin'),{statusCode:409});
});
test('approval privileges come from the authenticated session, never from the request body',async()=>{
 const calls=[];let role='platform_admin';
 const ctx={requireConsoleAccess:()=>({username:'own',role}),requireCsrf:()=>true,getWorkflow:async()=>({approve:async(...args)=>calls.push(args),approveHours:async(...args)=>calls.push(args)}),actor:()=> 'own',readJson:async()=>({role:'super_admin',superAdmin:true}),audit:async()=>{},json:(_res,status,body)=>({status,body})};
 const req={method:'POST',headers:{host:'localhost',origin:'http://localhost'}};
 await workflowRoutes(req,null,new URL('http://localhost/api/volunteer/workflow/events/x/approve'),ctx);
 assert.deepEqual(calls[0],['x','own','platform_admin']);role='super_admin';
 await workflowRoutes(req,null,new URL('http://localhost/api/volunteer/workflow/hours/h/approve'),ctx);
 assert.deepEqual(calls[1],['h','own','super_admin']);
});
test('legacy verified super administrator completes the HTTP workflow from creation to repeated posting',async()=>{
 const f=fixture(), legacy={...student,studentId:'',role:'super_admin'};
 const session={username:'synthetic-super',role:'super_admin'};
 const ctx={requireConsoleAccess:()=>session,requirePortalSession:()=>session,requireCsrf:()=>true,getWorkflow:async()=>f.w,getAccount:async()=>legacy,actor:()=>legacy.accountId,readJson:async req=>req.body||{},audit:async()=>{},json:(_res,status,body)=>({status,body})};
 const call=async(path,body={})=>workflowRoutes({method:'POST',headers:{host:'localhost',origin:'http://localhost'},body},null,new URL(`http://localhost/api/${path}`),ctx);
 const created=await call('volunteer/workflow/events',{...body,submit:true});assert.equal(created.status,201);const id=created.body.result._id;
 await call(`volunteer/workflow/events/${id}/approve`);await call(`volunteer/workflow/events/${id}/publish`);
 const signup=await call(`portal/workflow/events/${id}/register`);assert.equal(signup.status,201);assert.equal(legacy.studentId,'');
 const registration=f.rows[WF.registrations][0];assert.equal(registration.学号,student.studentId);
 await call(`volunteer/workflow/registrations/${registration._id}/confirm`);
 await call(`volunteer/workflow/registrations/${registration._id}/checkin`,{note:'合成现场核验'});
 await call(`volunteer/workflow/registrations/${registration._id}/review`);const ledger=f.rows[WF.ledger][0];
 await call(`volunteer/workflow/hours/${ledger._id}/approve`);
 assert.equal((await call(`volunteer/workflow/hours/${ledger._id}/post`)).body.result.serviceHours,2);
 assert.equal((await call(`volunteer/workflow/hours/${ledger._id}/post`)).body.result.serviceHours,2);
});
test('console snapshot reads only three display tables and remains fresh; evidence reads stay complete',async()=>{
 const calls=[],rows=Object.fromEntries(Object.values(WF).map(t=>[t,[]]));
 const w=createWorkflow({listRows:async table=>{calls.push(table);return structuredClone(rows[table]);}});
 const ctx={requireConsoleAccess:()=>({role:'super_admin'}),getWorkflow:async()=>w,json:(_res,status,body)=>({status,body})};
 const req={method:'GET',headers:{host:'localhost'}};
 const out=await workflowRoutes(req,null,new URL('http://localhost/api/volunteer/workflow'),ctx);
 assert.equal(out.status,200);assert.deepEqual(calls.sort(),[WF.events,WF.registrations,WF.ledger].sort());
 assert.deepEqual(Object.keys(out.body).sort(),['ok','testOnly','events','registrations','ledger'].sort());
 rows[WF.events].push({_id:'external-change',状态:'待审核'});calls.length=0;
 assert.equal((await w.overview()).events[0]._id,'external-change');assert.equal(calls.length,3);
 calls.length=0;await w.read();assert.equal(calls.length,6);
});
