import assert from 'node:assert/strict';
import {test} from 'node:test';
import {randomUUID} from 'node:crypto';
import {createWorkflow,WF} from '../lib/events/workflow.js';
import {bloodRosterDrafts,registrationResult} from '../lib/events/blood-roster.js';
import {campusLoginIdentifier} from '../public/app/portal/campus-login.js';
import {photoType,storePhoto} from '../lib/events/attendance-photo.js';
import {Readable} from 'node:stream';
const templates=[{_id:'template1',序号:'周一',点位:'新街口中央',活动时间:'上午 11~15点'},{_id:'template2',序号:'周一',点位:'新街口印象汇',活动时间:'上午 10~14点'}];
const rules={monday:'2026-10-05',week:45,capacity:1,serviceHours:2,trainingHours:0.5,travelHours:1};
const student={accountId:'synthetic',studentId:'999990001',realName:'合成同学',email:'999990001@smail.nju.edu.cn',emailVerified:true};
function fixture(){let n=0,time=Date.parse('2026-10-04T12:00:00+08:00');const tables=Object.fromEntries(Object.values(WF).map(t=>[t,[]]));tables['市血液献血车排班表（模板表）']=templates;
 const base={async listRows(t,_v,_o,_c,s=0,l=500){return structuredClone(tables[t].slice(s,s+l));},async appendRow(t,row){const r={...row,_id:`row${++n}`};tables[t].push(r);return{_id:r._id};},async updateRow(t,id,patch){Object.assign(tables[t].find(r=>r._id===id),patch);}};
 return {tables,w:createWorkflow(base,{now:()=>time}),clock:v=>{time=Date.parse(v);}};
}
async function prepare(f){const out=await f.w.prepareBloodWeek(rules,'owner');for(const e of out.events){await f.w.approve(e._id,'reviewer');await f.w.publish(e._id);}return out.events;}
test('campus login normalizes student ID with suffix and retains saved email; rejects malformed identity',()=>{assert.equal(campusLoginIdentifier('231250082','nju.edu.cn'),'231250082@nju.edu.cn');assert.equal(campusLoginIdentifier('231250082@smail.nju.edu.cn','nju.edu.cn'),'231250082@smail.nju.edu.cn');assert.throws(()=>campusLoginIdentifier('x','smail.nju.edu.cn'));assert.throws(()=>campusLoginIdentifier('231250082','evil.example'));});
test('roster preserves weekday/point/shift combinations and rejects duplicates or invalid dates',()=>{const rows=bloodRosterDrafts(templates,rules);assert.equal(rows[0].blood.start,'2026-10-05T11:00:00+08:00');assert.equal(rows[1].location,'新街口印象汇');assert.throws(()=>bloodRosterDrafts(templates,{...rules,monday:'2026-10-06'}));assert.throws(()=>bloodRosterDrafts([...templates,templates[0]],rules));assert.throws(()=>bloodRosterDrafts(templates,{...rules,monday:'2026-02-30'}));});
test('weekly prepare is idempotent, rejects altered rules; overlapping pending shifts are blocked',async()=>{const f=fixture(),events=await prepare(f);assert.equal((await f.w.prepareBloodWeek(rules,'owner')).count,2);assert.equal(f.tables[WF.events].length,2);await assert.rejects(f.w.prepareBloodWeek({...rules,serviceHours:4},'owner'),{statusCode:409});await f.w.register(events[0]._id,student);await assert.rejects(f.w.register(events[1]._id,student),{statusCode:409});});
test('leave is owner bound, blocks checkin pending approval; approved leave frees capacity for replacement',async()=>{const f=fixture(),[e]=await prepare(f);const a=await f.w.register(e._id,student);await f.w.confirm(a._id);await assert.rejects(f.w.requestLeave(a.报名ID,{accountId:'other'},'合成请假'),{statusCode:404});await f.w.requestLeave(a.报名ID,student,'合成请假');await assert.rejects(f.w.checkin(a._id,'checker','到场'),{statusCode:409});const second={...student,accountId:'second',studentId:'999990002',email:'999990002@smail.nju.edu.cn'};await assert.rejects(f.w.register(e._id,second,{replacement:true}),{statusCode:409});await f.w.decideLeave(a._id,true,'准假');const b=await f.w.register(e._id,second,{replacement:true});await f.w.confirm(b._id);assert.equal(b.报名类型,'替补');assert.equal(f.tables[WF.registrations][0].报名状态,'已请假');});
test('attendance is private, shift bounded, manual review gated; posting remains idempotent',async()=>{const f=fixture(),[e]=await prepare(f),r=await f.w.register(e._id,student);await f.w.confirm(r._id);await assert.rejects(f.w.checkin(r._id,'checker','到场'),{statusCode:409});await assert.rejects(f.w.submitAttendance(r.报名ID,student,randomUUID()),{statusCode:409});f.clock('2026-10-05T11:15:00+08:00');await assert.rejects(f.w.submitAttendance(r.报名ID,{accountId:'other'},randomUUID()),{statusCode:404});await f.w.submitAttendance(r.报名ID,student,randomUUID());assert.equal(f.tables[WF.checkins].length,0);await f.w.checkin(r._id,'checker','核对现场照片与日期时间');const l=await f.w.reviewHours(r._id,'checker');await f.w.approveHours(l._id,'approver');assert.equal((await f.w.post(l._id)).serviceHours,2);assert.equal((await f.w.post(l._id)).serviceHours,2);});
test('explicit failure and stop states are visible; stopped shifts deny registration and attendance',async()=>{const f=fixture(),[e]=await prepare(f),r=await f.w.register(e._id,student);await f.w.reject(r._id,'合成未入选原因');assert.equal(registrationResult(f.tables[WF.registrations][0]),'报名失败');await f.w.stop(e._id,'合成停点');await assert.rejects(f.w.register(e._id,{...student,accountId:'other'}),{statusCode:409});});
test('replacement is limited to two weeks, photo signatures and streaming size are enforced',async()=>{const f=fixture();const out=await f.w.prepareBloodWeek({...rules,monday:'2026-11-02'},'owner');await f.w.approve(out.events[0]._id,'reviewer');await f.w.publish(out.events[0]._id);await assert.rejects(f.w.register(out.events[0]._id,student,{replacement:true}),{statusCode:409});assert.throws(()=>photoType(Buffer.from('<html>unsafe image content</html>')));await assert.rejects(storePhoto(Readable.from([Buffer.alloc(4*1024*1024+1)])),{statusCode:413});});
