import assert from 'node:assert/strict';
import {test} from 'node:test';
import {createWorkflow,WF} from '../lib/events/workflow.js';
function fixture(fault=''){
 let seq=0,failed=false;const tables=Object.fromEntries(Object.values(WF).map(name=>[name,[]]));
 const base={async listRows(table,_v,_o,_c,start=0,limit=500){return structuredClone(tables[table].slice(start,start+limit));},async appendRow(table,row){const r={...row,_id:`r-${++seq}`};tables[table].push(r);return {_id:r._id};},async updateRow(table,id,patch){Object.assign(tables[table].find(r=>r._id===id),patch);}};
 const workflow=createWorkflow(base,{onStep:async step=>{if(step===fault&&!failed){failed=true;throw Error('synthetic interrupted write');}}});
 return {tables,workflow};
}
const body={name:'合成工位值班',date:'2026-10-04',slot:'上午',position:'签到岗',capacity:1,serviceHours:2,trainingHours:0.5,travelHours:1,location:'测试地点',work:'合成现场服务'};
const student={accountId:'synthetic-account',studentId:'999990001',realName:'测试同学',email:'999990001@smail.nju.edu.cn',emailVerified:true};
async function cycle(f){const w=f.workflow;const e=await w.create(body,'organizer');await assert.rejects(w.publish(e._id),{statusCode:409});await assert.rejects(w.approve(e._id,'organizer'),{statusCode:403});await w.approve(e._id,'reviewer');await w.publish(e._id);const r=await w.register(e._id,student);await w.confirm(r._id);await w.checkin(r._id,'checker','合成到场核验');const l=await w.reviewHours(r._id,'hour-checker');await assert.rejects(w.approveHours(l._id,'hour-checker'),{statusCode:403});await w.approveHours(l._id,'hour-approver');return {e,r,l};}
test('application to approved hours and repeated posting keep exactly one ledger and totals',async()=>{const f=fixture();const {r,l}=await cycle(f);assert.equal((await f.workflow.reviewHours(r._id,'hour-checker'))._id,l._id);const first=await f.workflow.post(l._id);const second=await f.workflow.post(l._id);assert.deepEqual(first,second);assert.equal(first.serviceHours,2);assert.equal(first.trainingHours,0.5);assert.equal(f.tables[WF.profiles][0].志愿时长,'2');assert.equal(f.tables[WF.ledger].length,1);const exportDraft=await f.workflow.exportDraft(f.tables[WF.events][0]._id);assert.equal(exportDraft.rows[0].服务时长,2);assert.equal(exportDraft.rows[0].培训时长,0.5);assert.equal(exportDraft.writes,false);});
for(const step of ['summary','profile','registration'])test(`retry after durable ${step} partial success does not add twice`,async()=>{const f=fixture(step);const {l}=await cycle(f);await assert.rejects(f.workflow.post(l._id),/interrupted/);const result=await f.workflow.post(l._id);assert.equal(result.serviceHours,2);assert.equal(f.tables[WF.summaries].length,1);assert.equal(f.tables[WF.profiles].length,1);assert.equal(f.tables[WF.registrations][0].录入状态,'网站已入账');});
test('concurrent confirmation enforces capacity and unconfirmed cannot check in',async()=>{const f=fixture(),w=f.workflow;const e=await w.create(body,'organizer');await w.approve(e._id,'reviewer');await w.publish(e._id);const a=await w.register(e._id,student);await assert.rejects(w.register(e._id,{...student,accountId:'second',studentId:'999990002',email:'999990002@smail.nju.edu.cn'}),{statusCode:409});const b={...a,_id:'legacy-pending',账号ID:'second',学号:'999990002'};f.tables[WF.registrations].push(b);const out=await Promise.allSettled([w.confirm(a._id),w.confirm(b._id)]);assert.equal(out.filter(r=>r.status==='fulfilled').length,1);await assert.rejects(w.checkin(b._id,'checker','合成到场'),{statusCode:409});});
test('changed evidence and duplicate durable ledger fail closed',async()=>{const f=fixture();const {r,l}=await cycle(f);f.tables[WF.checkins][0].学号='other';await assert.rejects(f.workflow.post(l._id),{statusCode:409});f.tables[WF.checkins][0].学号=student.studentId;f.tables[WF.ledger].push({...f.tables[WF.ledger][0],_id:'duplicate'});await assert.rejects(f.workflow.post(l._id),{statusCode:409});assert.equal(f.tables[WF.profiles].length,0);});
test('restart after partial success reconstructs totals from persisted approved rows',async()=>{const f=fixture('summary');const {l}=await cycle(f);await assert.rejects(f.workflow.post(l._id));const base={async listRows(t,_v,_o,_c,s=0,n=500){return structuredClone(f.tables[t].slice(s,s+n));},async appendRow(t,row){const r={...row,_id:`restart-${t}`};f.tables[t].push(r);return {_id:r._id};},async updateRow(t,id,p){Object.assign(f.tables[t].find(r=>r._id===id),p);}};const w=createWorkflow(base);assert.equal((await w.post(l._id)).serviceHours,2);assert.equal(f.tables[WF.summaries].length,1);});

test('manual rule or approved hours changes cannot silently alter a posted total',async()=>{const f=fixture();const {l}=await cycle(f);f.tables[WF.events][0].服务时长='5';await assert.rejects(f.workflow.post(l._id),{statusCode:409});f.tables[WF.events][0].服务时长='2';f.tables[WF.ledger][0].服务时长='5';await assert.rejects(f.workflow.post(l._id),{statusCode:409});assert.equal(f.tables[WF.profiles].length,0);});

test('one action verifies attendance and drafts adjusted hours; retry and later posting are idempotent',async()=>{
 const f=fixture(),w=f.workflow,e=await w.create(body,'owner');await w.approve(e._id,'reviewer');await w.publish(e._id);const r=await w.register(e._id,student);await w.confirm(r._id);
 const payload={note:'现场已核验',serviceHours:1.5,trainingHours:1,travelHours:0};const l=await w.checkinAndReview(r._id,'checker',payload);
 assert.equal((await w.checkinAndReview(r._id,'checker',payload))._id,l._id);assert.equal(f.tables[WF.checkins].length,1);assert.equal(f.tables[WF.ledger].length,1);
 await assert.rejects(w.checkinAndReview(r._id,'checker',{...payload,serviceHours:9}),{statusCode:409});await w.approveHours(l._id,'approver');assert.equal((await w.post(l._id)).serviceHours,1.5);assert.equal((await w.post(l._id)).serviceHours,1.5);
 f.tables[WF.ledger][0].服务时长='8';await assert.rejects(w.post(l._id),{statusCode:409});
});
test('invalid adjusted hours fail before any attendance write',async()=>{const f=fixture();await assert.rejects(f.workflow.checkinAndReview('missing','checker',{serviceHours:-1,note:'现场'}),{statusCode:400});assert.equal(f.tables[WF.checkins].length,0);});
test('approved adjusted training and travel hours are preserved in the export',async()=>{const f=fixture(),w=f.workflow,e=await w.create(body,'owner');await w.approve(e._id,'reviewer');await w.publish(e._id);const r=await w.register(e._id,student);await w.confirm(r._id);const l=await w.checkinAndReview(r._id,'checker',{note:'已核验',serviceHours:1.5,trainingHours:2,travelHours:0});await w.approveHours(l._id,'approver');const draft=await w.exportDraft(e._id);assert.equal(draft.rows[0].服务时长,1.5);assert.equal(draft.rows[0].培训时长,2);assert.equal(draft.rows[0].交通时长,0);});
