import {test} from 'node:test';import assert from 'node:assert/strict';
import {workflowMode,PRODUCTION_VOLUNTEER_BASE,TEST_WORKFLOW_BASE} from '../lib/events/workflow-mode.js';
import {generatedBloodEvents,bloodSourceOccupied} from '../lib/events/blood-source.js';
import {syncBloodBooking} from '../lib/events/blood-booking.js';
const slot={_id:'source',日期:'2026-10-12',点位:'新街口中央',活动时间:'上午 11~15点',周次:46};
const registration={报名ID:'website-one',账号ID:'account',学号:'999990001',姓名:'合成测试',邮箱:'999990001@smail.nju.edu.cn'};
test('production opt-in cannot write to another Base; test opt-in cannot enable production',()=>{assert.equal(workflowMode({PLATFORM_WORKFLOW_MODE:'production',SEATABLE_VOLUNTEER_BASE_UUID:PRODUCTION_VOLUNTEER_BASE}).bloodSourceTable,'市献血车汇总');for(const env of [{PLATFORM_TEST_WORKFLOW:'true',SEATABLE_VOLUNTEER_BASE_UUID:PRODUCTION_VOLUNTEER_BASE},{PLATFORM_WORKFLOW_MODE:'production',SEATABLE_VOLUNTEER_BASE_UUID:TEST_WORKFLOW_BASE},{}])assert.throws(()=>workflowMode(env));});
test('linked identities and pending source rows occupy slots, empty arrays do not',()=>{assert.ok(bloodSourceOccupied({...slot,报名结果:'待审核'}));assert.ok(bloodSourceOccupied({...slot,姓名2:['合成']}));assert.equal(Boolean(bloodSourceOccupied({...slot,姓名2:[],邮箱2:[]})),false);});
test('each row is a position; partial stop removes only that position',()=>{const e=generatedBloodEvents([{...slot,报名结果:'停点'},{...slot,_id:'second',报名结果:'可报名'},{...slot,_id:'third',报名结果:'待审核'}],0)[0];assert.equal(e.状态,'报名中');assert.equal(e.容量,2);assert.equal(JSON.parse(e.报名页配置).sourceOccupied,1);assert.equal(generatedBloodEvents([{...slot,报名结果:'停点'}],0)[0].状态,'停点');});
test('production reservation reconciles lost acknowledgements and releases only owned rows',async()=>{const rows=[{...slot,报名结果:'可报名'}];let writes=0;const base={async listRows(){return structuredClone(rows);},async getRow(_t,id){return structuredClone(rows.find(r=>r._id===id));},async updateRow(_t,id,patch){writes++;Object.assign(rows.find(r=>r._id===id),patch);if(writes===1)throw Error('lost acknowledgement');}};const event=generatedBloodEvents(rows,0)[0];assert.equal(await syncBloodBooking(base,'source',event,registration),'source');assert.equal(rows[0].报名结果,'待审核');assert.equal(JSON.parse(generatedBloodEvents(rows,0,new Set([registration.报名ID]))[0].报名页配置).sourceOccupied,0);await syncBloodBooking(base,'source',event,registration,'成功');assert.equal(rows[0].报名结果,'成功');await syncBloodBooking(base,'source',event,registration,'可报名');assert.equal(rows[0].网站报名ID,'');assert.equal(rows[0].姓名,'');assert.equal(rows[0].报名结果,'可报名');});
test('new reservation must not overwrite an NJUTable claim made during reread',async()=>{let writes=0;const base={async listRows(){return [{...slot,报名结果:'可报名'}];},async getRow(){return {...slot,报名结果:'待审核',姓名:'其他合成报名'};},async updateRow(){writes++;}};await assert.rejects(syncBloodBooking(base,'source',generatedBloodEvents([slot],0)[0],registration),{statusCode:409});assert.equal(writes,0);});

test('orphan source markers occupy capacity until reconciled',()=>{const e=generatedBloodEvents([{...slot,网站报名ID:'missing-website-row',报名结果:'待审核'}],0)[0];assert.equal(JSON.parse(e.报名页配置).sourceOccupied,1);});
import {createWorkflow,WF} from '../lib/events/workflow.js';
test('formal workflow reserves once, rejects competing signup, confirms and releases a real source position',async()=>{
 const tables=Object.fromEntries(Object.values(WF).map(t=>[t,[]]));tables.source=[{...slot,报名结果:'可报名'}];let n=0;
 const base={async listRows(t,_v,_o,_c,start=0,limit=500){return structuredClone(tables[t].slice(start,start+limit));},async getRow(t,id){return structuredClone(tables[t].find(r=>r._id===id));},async appendRow(t,row){const r={...row,_id:`synthetic-${++n}`};tables[t].push(r);return {_id:r._id};},async updateRow(t,id,patch){Object.assign(tables[t].find(r=>r._id===id),patch);}};
 const w=createWorkflow(base,{mode:'production',bloodSourceTable:'source',now:()=>Date.parse('2026-10-06T00:00:00+08:00')});
 const account={accountId:'account',studentId:'999990001',realName:'合成测试',email:'999990001@smail.nju.edu.cn',emailVerified:true};const event=(await w.publicRead()).events[0];
 const r=await w.register(event._id,account);assert.equal(tables.source[0].网站报名ID,r.报名ID);assert.equal(tables.source[0].报名结果,'待审核');await w.register(event._id,account);assert.equal(tables[WF.registrations].length,1);
 await assert.rejects(w.register(event._id,{...account,accountId:'second',studentId:'999990002',email:'999990002@smail.nju.edu.cn'}),{statusCode:409});
 await w.confirm(r._id);assert.equal(tables.source[0].报名结果,'成功');assert.equal(tables[WF.registrations][0].报名状态,'已确认');await w.requestLeave(r.报名ID,account,'合成请假原因');await w.decideLeave(r._id,true,'合成审批');assert.equal(tables.source[0].报名结果,'可报名');assert.equal(tables.source[0].网站报名ID,'');assert.equal(tables[WF.registrations][0].报名状态,'已请假');
});
